-- Generated by `supabase db pull` on 2026-08-23. Do not hand-edit beyond this
-- comment: it is already recorded as applied in the remote migration history,
-- so local edits will not re-run and will only drift from what the database
-- actually has.
--
-- Contents are grant and default-privilege normalisation, not structural
-- change: `0001_scans_rls.sql` already matched production on the table,
-- constraints, RLS and all three policies, and the diff confirmed it by
-- containing none of them.
--
-- The part worth reading is the default-privilege block. This project carries
-- Supabase's defaults, under which a new table created by postgres in `public`
-- is granted to `anon` the moment it exists — and `anon` is the key that ships
-- in the browser bundle. RLS is the only thing between a new table and the
-- public internet. Enable it before putting data in one.
--
-- Note also `revoke all on table "public"."scans" from "anon"`: that table is
-- reachable only by `authenticated` and `service_role`, so an unauthenticated
-- request is refused on privileges before RLS is consulted.

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

revoke all on table "public"."scans" from "anon";

revoke all on table "public"."scans" from "authenticated";

grant delete, insert, select, update on table "public"."scans" to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

